### ISSUE TITLE
setImmediate is not defined error

### ISSUE THREAD

**Issue by magicxiao** [nickewing/line-reader#19]
there is a bug for version 0.2.4.
0.2.3 is ok.
stack:
node_modules/line-reader/lib/line_reader.js:130
          setImmediate(readNext);
ReferenceError: setImmediate is not defined
  at newRead (node_modules/line-reader/lib/line_reader.js:130:11)
  at then.finalFn (node_modules/line-reader/lib/line_reader.js:162:7)
  at node_modules/line-reader/lib/line_reader.js:112:9
  at node_modules/line-reader/lib/line_reader.js:56:13
  at Object.wrapper [as oncomplete] (fs.js:362:17)

**Comment by nickewing** [comment]
NodeJS 0.10.0 introduces `setImmediate`.  I've added the required node version to the package.json.
